### ISSUE TITLE
自动计算弹出菜单的宽度

### ISSUE THREAD

**Issue by afc163** [react-component/dropdown#1]
如果不设置，菜单宽度按以下原则计算：

1. 取触发元素的宽度
2. 取菜单文字的最大宽度
3. 取两者的大值

这样如何？

**Comment by yiminghe** [comment]
样式就可以了   https://github.com/ant-design/ant-design/blob/73d89f46affbf137957540705c90361a633822e8/style/components/dropdown.less#L14

**Comment by afc163** [comment]
👍
