### ISSUE TITLE
setting hideAction = 'mouseLeave' unexpectedly hides the menu when the mouse leaves the trigger control and enters the menu area

### ISSUE THREAD

**Issue by LaurieSReynolds** [react-component/dropdown#18]
I am using the latest 1.4.10 version of the dropdown.

I would like the dropdown to hide when the user moves the mouse off the menu or if the user clicks outside of the menu.   Setting hideAction to 'mouseLeave' seemed to be the way to accomplish this.

Setting hideAction results in the menu hiding when the user moves from the trigger button to the menu.

Is there another prop that I should be using?

To see the behavior, modify the examples/simple.js in the repo
 ~ add hideAction prop to the Dropdown as in below.

ReactDOM.render(<div style={{ margin: 20 }}>
  <div style={{ height: 100 }}/>
  <div>
    <Dropdown
      trigger={['click']}
      overlay={menu}
      animation="slide-up"
      onVisibleChange={onVisibleChange}
      hideAction={['click', 'mouseLeave']}
    >
      <button style={{ width: 100 }}>open</button>
    </Dropdown>
  </div>
</div>, document.getElementById('__react-content'));

**Comment by benjycui** [comment]
An online demo will be better.

**Comment by benjycui** [comment]
Close for no response.
