### ISSUE TITLE
Bug v4.0.1 closes dropdown when overlay click

### ISSUE THREAD

**Issue by Arttse** [react-component/dropdown#221]
## Bug report
Affected: `rc-dropdown@4.0.1`
See: https://codesandbox.io/s/rc-dropdown-v4-0-1-overlay-click-visible-false-bug-ppo3hl-ppo3hl?file=/src/App.tsx

### Steps to reproduce
1. Click on "open" button
2. Click on appeared "disabled" menu item

#### Current behavior
Dropdown closes

#### Expected behavior
Dropdown not closes

### Additional
When using `rc-dropdown@3.6.2` there is no problem

**Comment by Arttse** [comment]
I also found that the examples use old version of `rc-dropdown`. Example https://dropdown-react-component.vercel.app/?path=/story/rc-dropdown--simple

**Comment by afc163** [comment]
PR welcome~

**Comment by ismajl-ramadani** [comment]
> PR welcome~

I would do a PR, but can you share any thought on how to implement this properly? I'm thinking to pass a prop that is a flag for the onClick event. I see that onPopupClick of Trigger calls onClick handler, and then setTriggerVisible(false); is called immediately, and by passing that prop It would stop that call, hence the dropdown will retain its state.

**Comment by Arttse** [comment]
Maybe it's not a bug, but a feature. It's just that it wasn't described properly and that's why it's confusing to others.

In v4, now you need to manage the closing of dropdown yourself. Like that:

```tsx
import { useState } from "react";
import Dropdown from "rc-dropdown";
import type { DropdownProps } from "rc-dropdown/lib/Dropdown";
import Menu, { MenuItem, Divider, MenuProps } from "rc-menu";
import "rc-dropdown/assets/index.css";
import "rc-menu/assets/index.css";

export default function App() {
  const [visible, setVisible] = useState(false);

  const onSelect: Required<MenuProps>["onSelect"] = ({ key }) => {
    console.log(`${key} selected`);
    // here close dropdown on select menu item
    setVisible(false);
  };

  const onVisibleChange: Required<DropdownProps>["onVisibleChange"] = (
    visible
  ) => {
    console.log("visible", visible);
    setVisible(visible);
  };

  const menuCallback = () => (
    <Menu onSelect={onSelect}>
      <MenuItem disabled>disabled</MenuItem>
      <MenuItem key="1">one</MenuItem>
      <Divider />
      <MenuItem key="2">two</MenuItem>
    </Menu>
  );

  return (
    <Dropdown
      trigger={["click"]}
      overlay={menuCallback}
      animation="slide-up"
      // controlled
      visible={visible}
      onVisibleChange={onVisibleChange}
    >
      <button style={{ width: 100 }}>open</button>
    </Dropdown>
  );
}
```

Now you can control at what action to close dropdown with any `overlay`. Therefore, I close the issue.
