### ISSUE TITLE
minOverlayWidthMatchTrigger为true时，dropdown定位不准确

### ISSUE THREAD

**Issue by cagen** [react-component/dropdown#27]
在Trigger的宽度大于overlay的宽度的情形下，当minOverlayWidthMatchTrigger为true时（rc-dropdown的默认值）且 placement 不是靠左的时候，第一次显示dropdown的位置会偏移。（再显示一次就会正常了）

例子：
https://codepen.io/anon/pen/aymyVB?editors=001

我找到的可能的原因是dropdown是先按照原始宽度做的align，然后再根据Trigger的宽度去改变dropdown的宽度，但dropdown本身却没有重新align：
https://github.com/react-component/dropdown/blob/master/src/Dropdown.jsx#L104

1. 第一次显示
![image](https://user-images.githubusercontent.com/5174809/28904230-f3ae3eb4-783b-11e7-899f-70aa6ed2f8a2.png)

2. 宽度调整
![image](https://user-images.githubusercontent.com/5174809/28904241-051fce92-783c-11e7-8e39-9c875468adb4.png)

3. 最终显示
![image](https://user-images.githubusercontent.com/5174809/28904257-1a4fffbc-783c-11e7-993c-1aa4054f501b.png)

**Comment by afc163** [comment]
It is a bug indeed. And I fix this in antd by lock the `minOverlayWidthMatchTrigger` to `true` in antd: https://github.com/ant-design/ant-design/commit/144c67f054ee54911ea56f50a3504d57f9928ea2

Could you try to fix it and give us a PR?
