### ISSUE TITLE
希望增加配置，可以允许 overlay 的宽度，小于 root 的宽度

### ISSUE THREAD

**Issue by eternalsky** [react-component/dropdown#31]
目前的逻辑，overlay 的宽度必须大于等于 root，有些 dropdown 的宽度，在实际场景中需要小于 root，是否可以提供配置，关闭这个操作？

**Comment by afc163** [comment]
https://github.com/react-component/dropdown/blob/master/src/Dropdown.jsx#L108

**Comment by lpgray** [comment]
高效

**Comment by afc163** [comment]
文档没写，帮我们写下如何？

**Comment by eternalsky** [comment]
好
