### ISSUE TITLE
Pass dropdown visible state to overlay

### ISSUE THREAD

**Issue by cagen** [react-component/dropdown#35]
Hi, When I pass dropdown visible state to overlay and set the trigger to hover, the overlay prop is not update correctly.
[Demo](https://codepen.io/anon/pen/xXWzgy?editors=0010)

```js
// You should fork and save if you had updated this CodePend and want to send it to others.
// Note: antd.locales are only support by `dist/antd`
const { Dropdown } = antd;

class Div extends React.Component {
  componentDidMount () {
    console.log('overlay mount', this.props.visible)  
  }
  
  componentDidUpdate () {
    console.log('overlay update', this.props.visible)  
  }
  
  render () {
    return <div className='overlay-container'>Overlay</div>
  }
}

class Test extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      visible: false
    }
    this.handleVisibleChange = this.handleVisibleChange.bind(this)
  }
  
  handleVisibleChange (visible) {
    console.log('visible change', visible)
    this.setState({ visible })
  }
  
  render () {
    return (
      <div>
        <Dropdown
          placement='bottomLeft'
          trigger={['click']}
          onVisibleChange={this.handleVisibleChange}
          overlay={<Div visible={this.state.visible} />}
        >
          <span className='trigger-text'>Click Text</span>
        </Dropdown>
        <Dropdown
          placement='bottomRight'
          trigger={['hover']}
          mouseEnterDelay={0}
          onVisibleChange={this.handleVisibleChange}
          overlay={<Div visible={this.state.visible} />}
        >
          <span>Hover Text</span>
        </Dropdown>
      </div>
      
    )
  }
}

ReactDOM.render(
  <Test />
, mountNode);
```

When the mouse leave the Trigger, the output of the console is like this:
![image](https://user-images.githubusercontent.com/5174809/31382541-a7c69696-ad7d-11e7-9405-22d6bf1f4179.png)
**overlay is updated before the visible has changed, and the value is true not false**  

And it also related to the mouseEnterDelay prop. When mouseEnterDelay is not set to 0 (0 is the default prop value of rc-trigger), the result is different:
![image](https://user-images.githubusercontent.com/5174809/31382183-6e80ec34-ad7c-11e7-8f83-e1af6ed278df.png)
**overlay is updated before the visible has changed too, but when the next enter event trigger, the overlay prop updated twice.**  

If the trigger is set to 'click'，everything works fine:
![image](https://user-images.githubusercontent.com/5174809/31382337-ee3d256e-ad7c-11e7-8960-ff35a39757a1.png)

**Comment by benjycui** [comment]
Yep, but why does your overlay care about `visible`?

**Comment by cagen** [comment]
In my particular case, My overlay need to update its content when the overlay is re-open.
I know that I could update the content in the parent component and pass it to the overlay as props. But in my case, the overlay is a relatively complex component which have a lot of data logic. I don't want them to mixed with the UI logic in the parent component which has some basic UI besides Dropdown.

**Comment by benjycui** [comment]
```jsx
<Dropdown destroyPopupOnHide />
```

And then you can generate new Data every time.

**Comment by benjycui** [comment]
See: https://github.com/react-component/trigger#props

**Comment by benjycui** [comment]
The issue you posted is difficult to change, and it doesn't affect users in most circumstance, so, just close, thanks.

**Comment by cagen** [comment]
Hmm, I did not notice that prop before. It could be a good way to solve my problem.
I think it might be a little expensive for my 'complex' overlay to re-render every time, but I will give it a try.
Many Thanks.
